export type AppIconName =
  | 'layout-dashboard'
  | 'users'
  | 'book-open'
  | 'package'
  | 'file-text'
  | 'receipt'
  | 'user-cog'
  | 'panel-left-open'
  | 'panel-left-close'
  | 'anvil'
  | 'chevron-up'
  | 'chevron-down'
  | 'chevrons-up-down'
  | 'menu';
